language: node_js
cache: npm
node_js:
  - node
git:
  depth: 5

script:
  - npm run build
  - npm test
  - npm run size

stages:
  - name: deploy
    if: branch = master AND commit_message !~ /(no-release)/

deploy:
  skip_cleanup: true
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm run release
