language: node_js
cache: npm
node_js:
  - node
git:
  depth: 5

jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm test
        - npm run size
    - stage: release
      script:
        - npm run build
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm run release -- --ci

stages:
  - test
  - name: release
    if: |
      branch = master AND \
      type = push AND \
      commit_message !~ /(no-release)/
